name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 60
          days-before-close: 7
          stale-issue-message: 'Эта задача неактивна в течение 60 дней. Она будет закрыта через 7 дней, если не будет активности.'
          stale-pull-request-message: 'Этот Pull Request неактивен в течение 60 дней. Он будет закрыт через 7 дней, если не будет активности.'
          close-issue-message: 'Эта задача была автоматически закрыта из-за отсутствия активности.'
          close-pull-request-message: 'Этот Pull Request был автоматически закрыт из-за отсутствия активности.'
          exempt-issue-labels: 'bug,enhancement,feature'
          exempt-pr-labels: 'bug,enhancement,feature'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
